-- ============================================================
-- SCRIPT DE LIMPIEZA (DROP TABLES)
-- Ejecutar antes de correr el nuevo DDL para evitar conflictos
-- ============================================================

-- 1. Incidentes (Dependen de casi todo el modelo)
DROP TABLE IF EXISTS PROBLEMA_RESUELTO;
DROP TABLE IF EXISTS PROBLEMA;
DROP TABLE IF EXISTS FUENTE_IMPACTA_OBJETO;

-- 2. Relaciones N:M y Linaje
DROP TABLE IF EXISTS LINAJE_DATOS;
DROP TABLE IF EXISTS EQUIPO_TRABAJA_OBJETO;
DROP TABLE IF EXISTS HERRAMIENTA_GESTIONA_ACTIVO;
DROP TABLE IF EXISTS OPERACION_VINCULADA_ACTIVO;

-- 3. Activos y Objetos
DROP TABLE IF EXISTS PROCESO;
DROP TABLE IF EXISTS TABLERO;
DROP TABLE IF EXISTS REPORTE;
DROP TABLE IF EXISTS OBJETO;
DROP TABLE IF EXISTS ACTIVO;
DROP TABLE IF EXISTS FASE_VIDA_ACTIVO;
DROP TABLE IF EXISTS DEFINICION_FUNCIONAL;

-- 4. Herramientas
DROP TABLE IF EXISTS HERRAMIENTA_OPEN_SOURCE;
DROP TABLE IF EXISTS SOFTWARE;
DROP TABLE IF EXISTS LICENCIA;
DROP TABLE IF EXISTS HERRAMIENTA;
DROP TABLE IF EXISTS PROVEEDOR;

-- 5. Accesos y Permisos
DROP TABLE IF EXISTS ACCESO_FUENTE_DATOS;
DROP TABLE IF EXISTS PERFIL_TIENE_PERMISO;
DROP TABLE IF EXISTS PERMISO;
DROP TABLE IF EXISTS PERFIL;
DROP TABLE IF EXISTS ROL;

-- 6. Fuentes de Datos
DROP TABLE IF EXISTS FUENTE_UBICADA_EN;
DROP TABLE IF EXISTS FUENTE_DE_DATOS;

-- 7. Geografía e Infraestructura
DROP TABLE IF EXISTS NUBE_EN_REGION;
DROP TABLE IF EXISTS DIRECCION_FISICA;
DROP TABLE IF EXISTS APLICACION;
DROP TABLE IF EXISTS UBICACION;
DROP TABLE IF EXISTS CALLE;
DROP TABLE IF EXISTS LOCALIDAD;
DROP TABLE IF EXISTS PROVINCIA;
DROP TABLE IF EXISTS PAIS;
DROP TABLE IF EXISTS REGION;

-- 8. Organización y Equipos
DROP TABLE IF EXISTS DIRIGE_EQUIPO;
DROP TABLE IF EXISTS PERTENECE_A_EQUIPO;
DROP TABLE IF EXISTS OPERACION;
DROP TABLE IF EXISTS EQUIPO;
DROP TABLE IF EXISTS DEPARTAMENTO;

-- 9. Sujetos y Actores (Tablas Padre)
DROP TABLE IF EXISTS ORGANIZACION;
DROP TABLE IF EXISTS EXTERNO;
DROP TABLE IF EXISTS MIEMBRO_UO;
DROP TABLE IF EXISTS PROFESIONAL;
DROP TABLE IF EXISTS ESPECIALIDAD;
DROP TABLE IF EXISTS PUESTO_TRABAJO;
DROP TABLE IF EXISTS SUJETO;

-- ============================================================
-- FIN DEL SCRIPT DE LIMPIEZA
-- ============================================================